config/routes.rb
Rails.application.routes.draw do
  resources :rsses

end

app/models/rss.rb
class Rss < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsses_controller.rb
class RssesController < ApplicationController
  before_action :set_rss, only: [:show, :edit, :update, :destroy]

  # GET /rsses
  # GET /rsses.json
  def index
    @rsses = Rss.all
  end

  # GET /rsses/1
  # GET /rsses/1.json
  def show
  end

  # GET /rsses/new
  def new
    @rss = Rss.new
  end

  # GET /rsses/1/edit
  def edit
  end

  # POST /rsses
  # POST /rsses.json
  def create
    @rss = Rss.new(rss_params)

    respond_to do |format|
      if @rss.save
        format.html { redirect_to @rss, notice: 'Rss was successfully created.' }
        format.json { render :show, status: :created, location: @rss }
      else
        format.html { render :new }
        format.json { render json: @rss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rsses/1
  # PATCH/PUT /rsses/1.json
  def update
    respond_to do |format|
      if @rss.update(rss_params)
        format.html { redirect_to @rss, notice: 'Rss was successfully updated.' }
        format.json { render :show, status: :ok, location: @rss }
      else
        format.html { render :edit }
        format.json { render json: @rss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsses/1
  # DELETE /rsses/1.json
  def destroy
    @rss.destroy
    respond_to do |format|
      format.html { redirect_to rsses_url, notice: 'Rss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rss
      @rss = Rss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rss_params
      params.require(:rss).permit(:url, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rsses_helper.rb
module RssesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeinyaRss</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rsses/_form.html.erb
<%= form_for(@rss) do |f| %>
  <% if @rss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss.errors.count, "error") %> prohibited this rss from being saved:</h2>

      <ul>
      <% @rss.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsses/edit.html.erb
<h1>Editing Rss</h1>

<%= render 'form' %>

<%= link_to 'Show', @rss %> |
<%= link_to 'Back', rsses_path %>

app/views/rsses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seinya RSS</h1>

<table>
  <thead>
    <tr>
      <th>URL</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsses.each do |rss| %>
      <tr>
        <td><%= rss.url %></td>
        <td><%= rss.category %></td>
        <td><%= link_to 'Show', rss %></td>
        <td><%= link_to 'Edit', edit_rss_path(rss) %></td>
        <td><%= link_to 'Delete', rss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rss URL', new_rss_path %>

app/views/rsses/new.html.erb
<h1>New Rss</h1>

<%= render 'form' %>

<%= link_to 'Back', rsses_path %>

app/views/rsses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @rss.url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @rss.category %>
</p>

<%= link_to 'Edit', edit_rss_path(@rss) %> |
<%= link_to 'Back', rsses_path %>